
project_id = "qrawynczvedffcvnympn"
app_version = "0.0.1"

[api]
host = "https://qrawynczvedffcvnympn.supabase.co" 
service_role_key = "YOUR-SERVICE-ROLE-KEY" # Don't worry about filling this in

[functions.account-created-listener]
verify_jwt = false

[[fetch.release]]
uri = "https://api.uniqode.com/v2/"
