
# Project configuration
project_id = "qrawynczvedffcvnympn"

# Functions configuration
[functions]
[functions.stripe-webhook]
verify_jwt = false

# External fetch configuration
[functions.external_fetch]
enabled = true
[[functions.external_fetch.origins]]
url = "https://api.uniqode.com/v2/"
