
# Project configuration
project_id = "qrawynczvedffcvnympn"

# Functions configuration
[functions]
[functions.stripe-webhook]
verify_jwt = false

# External fetch configuration 
[[functions.fetch.release]]
uri = "https://api.uniqode.com/v2/"
