
# Project configuration
project_id = "qrawynczvedffcvnympn"

# Enable external fetch for all functions
external_fetch = { enabled = true }

# Functions configuration
[functions]

[functions.stripe-webhook]
verify_jwt = false

