
project_id = "qrawynczvedffcvnympn"
app_version = "0.0.1"

[api]
host = "https://qrawynczvedffcvnympn.supabase.co" 
service_role_key = "YOUR-SERVICE-ROLE-KEY" # Don't worry about filling this in

[functions.platform-webhook]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-reader-notification]
verify_jwt = false

[functions.verify-stripe-session]
verify_jwt = false

[functions.send-email-notification]
verify_jwt = false

[functions.create-qr-checkout]
verify_jwt = false

[functions.create-tip-checkout]
verify_jwt = false


[functions.create-connect-account]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[[fetch.release]]
uri = "https://api.uniqode.com/v2/"
