
# This file defines your Supabase project configuration.
# It is used by Supabase CLI to support local development and CI/CD workflows.
#
# You can find more information on local development here:
# https://supabase.com/docs/guides/getting-started/local-development

[functions]

[functions.verify-stripe-session]
verify_jwt = true
