
# Project configuration
project_id = "qrawynczvedffcvnympn"

# Functions configuration
[functions]
[functions.stripe-webhook]
verify_jwt = false

# External fetch configuration for all functions
[functions]
external_fetch = true
